### PR TITLE
[ci] Mark flaky tests

### PR DESCRIPTION
**Pull request by vjuranek**

### CODE REVIEW

**Review by Naros — APPROVED** [review]

**Comment by Naros** [comment]
Hi @vjuranek, feel free to merge when its ready.

**Comment by jpechane** [comment]
@vjuranek OK, the system property to control flaky handling is not yet set in failsafe plugin configuration. Also the Github workflow does not set it yet. Please see Db2 repo for how it should be configured.

**Comment by vjuranek** [comment]
It seems that when I add ignoreing flaky tests nito this PR, it's still ignored. Sending in separate PR #29.

**Comment by Naros** [comment]
@vjuranek rebased on main with the `@Flaky` test support added, lets see how CI behaves.

**Comment by vjuranek** [comment]
Thanks @Naros , CI is now green, so looks ready to merge now.

**Pull request merged**
